### ISSUE TITLE
get access_token and clinet_id?

### ISSUE THREAD

**Issue by wumingyou126** [alohi/faxplus-python#1]
I can’t find a way to get access_token and clinet_id in the SDK, how do I get it?

**Comment by alohi** [comment]
Hi,

You should be able to get your client_id from the Profile section of the Admin account on which the API has been activated (Integrations).

Afterward, in order to get the access token, please follow the steps at the link here: https://apidoc.fax.plus/#authentication

Please note that the API is available for the Enterprise plan only
